sudo: required
services:
- docker
before_install:
- docker build . -t sdkks/ubuntu-bionic-workstation
- sudo apt-get update && sudo apt-get install -y sshpass
script:
- docker run -d -p 2222:22 sdkks/ubuntu-bionic-workstation
- sshpass -pdummyPassword ssh -o StrictHostKeyChecking=no -p2222 ubuntu@localhost
  echo no-op
deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
    && docker push sdkks/ubuntu-bionic-workstation
  on:
    branch: master
env:
  DOCKER_USER:
    secure: XadjNqUQNviMuI1ZZ5Nj81yd8r+XXFEvlI4ZzWVcdAs/fwpEd3CBth6qrYOmBbKxaH+Y0qxj7jju1D663sXc4FtIj4kaR4uhDbLrJ6zn7v0DSqTD6Ud31c/v0JpHdOrN7foPLp357YNq4178yGuYWCx3XAkm4Eb+6c1v6wX6gOFFSoVu+6IE/EMjR/2VogsFZ6vuRSMLdVAGflBkzpzF13Tfb0Lajp0wz/7Y6GvLJEOXP1Q2/4aqYLOb9Za0VvLwnniIRDNhLLDR4iwgTIvzTx+6BgNo0Dk7/9gHojmI5EXOgKZXbMb7tcSyGlxXwkkRLDqWqCoXA6iySg6AHXOs7kaElXhvU/aPE/7cMi0X6k1Z+9CbLGLPpFmckqJ7vYxX00MpG9lRG1CzP8TY88f4ldoA8GASe6zEKI3VlelJe6j+tEjCwaWutz1n0vJ6jPvUNxmmmueperXAbntxht+Q2ojn4+J8HPrDD921TaeJt3BwEvBW8Koy6Qfld7MXqFuo1GkTgQJapVjlQBgPTj3eQSuPeKcKIgxiDbXlgGRfSUW8tHQ/PbV0ti4TyOK10HjV0ZvNTJvoorjK6S5dnBEqjRWKUTnEohvpyV29BDGNuCnJJdY/fs15l1+esz4yfxLy0YQUAfvoKa6ZyCe1D0euFaI8g9CjPznqrEW9s6J4S1o=
  DOCKER_PASSWORD:
    secure: F8nKxa131CIDJl1LdNt+6cXEbYRAh+EN5q/7VpnRC3QLvE6wVbCDQoPuGzDFLTYdHY1iTBtVce0ZXKuXzIg5vAXT5Vu8LukVE4itOGUdg9rsiCR+sXpM6NqBaZJma1drPhUiG+orXbVfBPIzy1PN8P08P3AsCJwdPNgLGmlhvrDRUXTbBqB/iQnXXPf0Y5R/Z6R5AHndN0uCCK169/7JDe8qyTil/bJWXJAzavHvLo/+jSsoVIPEuoyVk7c/Vvyavq96N9UsbBBRch4Rh4tsQZ+DhYXf+IrHXu5xeNjxE53cVHxAnAwWU0K1bfGIrZSl7EvaH5OPYzaCCVLAmkfZKDw7+eG3H8Gm37SW6ca+ARoPaRd9z/oM036cUsNu+oK58HFGREPVZVVJOP4cQwTYn1s9kzRvCO07LIhDcqKJ8iLsxzr9CUjeXDup6GnQksexTh7o/q1ElUI5++cWzBBnEuo23R70Pqp3SRxHNG1QwOVNGYLB4O6v93Rc5shiNoGDg1KYaaDwIBcsVnF9rB0MVmxUY9qbfRSA6ipYOIefioXRcFE0z3ptpzIO19Y74QIRwDmKGS5Iggm8M70zbpKV8uIO+xt4do8hUAnsy/PmJ4oSJFuSFyYpj/6Gh2y4H/ZGUhpB+xB7iYpr7EK9APiH/aOD86a56iCgO5jXz2sUPqA=
